apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-go-app
  template:
    metadata:
      labels:
        app: my-go-app
    spec:
      containers:
        - name: my-go-app
          image: my-go-app:1.0
          ports:
            - containerPort: 8080
          env:
            - name: APP_ENV
              value: "prod"
          resources:
            limits:
              memory: "128Mi"
              cpu: "300m"
            requests:
              memory: "64Mi"
              cpu: "250m"
